"""
This is a setup.py script generated by py2applet

Usage:
    python3 ….py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ["docs","frp","main_cmdl.py","Resource","SupportLib","ui_kfq.py","ui_output.py","update_gui.sh","update_requirements.sh"]


# 存放所有要用到的文件资源，比如我放置了py_utils/这个是工具包文件夹，app所要显示的图片文件，以及自写模块放
# DATA_FILES = ['py_utils/', 'earth.icns', 'xxx1.py','xxx2.py','xxx3.py']


OPTIONS = {"iconfile": "logo.png",
           'plist': {
               'CFBundleName': 'MSL2',  # 应用名
               'CFBundleDisplayName': 'MSL2-Python-开服器',  # 应用显示名
               'CFBundleVersion': '1.0.0',  # 应用版本号
               'CFBundleIdentifier': 'MSL2-Python-David',  # 应用包名、唯一标识
               'NSHumanReadableCopyright': 'Copyright © 2022 MSL2 for David. All rights reserved.',  # 可读版权
               'includes': ['PySide6', 'sys', 'requests','subprocess','webbrowser','tqdm','SupportLib','os','tkinter','psutil','multitasking','retry']
           }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
