"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
APP_NAME = 'pyMSL for mac'
DATA_FILES = ['\\SupportLib\\','\\Resources\\']
OPTIONS = {
        'argv_emulation':True,
        'iconfile':'icon.icns',}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    plist={
            'CFBundleName':'pyMSL for mac',
            'CFBundleDisplayName':'pyMSL',
            'CFBundleGetInfoString':'The MSL2-Python on macOS!',
            'CFBundleIdentfier':'......',
            'CFBundleVersion':'22M9 Beta2 for mac',
            'CFBundleShortVersionString':'22M9B2',
            'NSHumanReadableCopyright':'Copyright MojaveHao and David2022 and all contributor 2022',},
    icludes=[
            'PySide6'
            'tqdm',
            'requests',
            'signal',
            'urllib',
            'multitasking',
            'retry',
            'traceback',
            'psutil',
            'tkinter',
           ]
)
