# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'download.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QMetaObject, QSize, Qt)
from PySide6.QtGui import (QCursor)
from PySide6.QtWidgets import (QComboBox, QGridLayout,
                               QHBoxLayout, QLabel, QPushButton, QSizePolicy,
                               QVBoxLayout, QWidget)


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(690, 145)
        Dialog.setMaximumSize(QSize(690, 145))
        self.horizontalLayout = QHBoxLayout(Dialog)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QWidget(Dialog)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(230, 145))
        self.widget.setMaximumSize(QSize(230, 145))
        self.verticalLayout_2 = QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        
        self.verticalLayout_2.addWidget(self.label)
        
        self.cbox_source = QComboBox(self.widget)
        self.cbox_source.addItem("")
        self.cbox_source.addItem("")
        self.cbox_source.addItem("")
        self.cbox_source.setObjectName(u"cbox_source")
        
        self.verticalLayout_2.addWidget(self.cbox_source)
        
        self.pbtn_ok1 = QPushButton(self.widget)
        self.pbtn_ok1.setObjectName(u"pbtn_ok1")
        self.pbtn_ok1.setCursor(QCursor(Qt.PointingHandCursor))
        
        self.verticalLayout_2.addWidget(self.pbtn_ok1)
        
        self.horizontalLayout.addWidget(self.widget)
        
        self.widget_2 = QWidget(Dialog)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setMinimumSize(QSize(230, 145))
        self.widget_2.setMaximumSize(QSize(230, 145))
        self.gridLayout = QGridLayout(self.widget_2)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label_2 = QLabel(self.widget_2)
        self.label_2.setObjectName(u"label_2")
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        
        self.cbox_type = QComboBox(self.widget_2)
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.setObjectName(u"cbox_type")
        self.cbox_type.setCursor(QCursor(Qt.PointingHandCursor))
        
        self.gridLayout.addWidget(self.cbox_type, 1, 0, 1, 1)
        
        self.pbtn_ok2 = QPushButton(self.widget_2)
        self.pbtn_ok2.setObjectName(u"pbtn_ok2")
        self.pbtn_ok2.setEnabled(True)
        self.pbtn_ok2.setCursor(QCursor(Qt.PointingHandCursor))
        
        self.gridLayout.addWidget(self.pbtn_ok2, 2, 0, 1, 1)
        
        self.horizontalLayout.addWidget(self.widget_2)
        
        self.widget_3 = QWidget(Dialog)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setMinimumSize(QSize(230, 145))
        self.widget_3.setMaximumSize(QSize(230, 145))
        self.verticalLayout = QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label_3 = QLabel(self.widget_3)
        self.label_3.setObjectName(u"label_3")
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        
        self.verticalLayout.addWidget(self.label_3)
        
        self.cbox_ver = QComboBox(self.widget_3)
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.addItem("")
        self.cbox_ver.setObjectName(u"cbox_ver")
        self.cbox_ver.setCursor(QCursor(Qt.PointingHandCursor))
        
        self.verticalLayout.addWidget(self.cbox_ver)
        
        self.pbtn_start_download = QPushButton(self.widget_3)
        self.pbtn_start_download.setObjectName(u"pbtn_start_download")
        self.pbtn_start_download.setCursor(QCursor(Qt.PointingHandCursor))
        
        self.verticalLayout.addWidget(self.pbtn_start_download)
        
        self.horizontalLayout.addWidget(self.widget_3)
        
        self.retranslateUi(Dialog)
        
        QMetaObject.connectSlotsByName(Dialog)
    
    # setupUi
    
    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"\u4e0b\u8f7d\u6e90\uff1a", None))
        self.cbox_source.setItemText(0, QCoreApplication.translate("Dialog", u"Xiaoyu\u6e90(MSL2)", None))
        self.cbox_source.setItemText(1, QCoreApplication.translate("Dialog",
                                                                   u"\u5b98\u65b9\u6e90(\u4e0b\u8f7d\u6162 \u4f46\u662f\u6700\u65b0\u7684)",
                                                                   None))
        self.cbox_source.setItemText(2, QCoreApplication.translate("Dialog", u"SakuraMirror(\u65e7\u7248\u672c)", None))
        
        self.pbtn_ok1.setText(QCoreApplication.translate("Dialog", u"\u786e\u8ba4", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"\u8981\u4e0b\u8f7d\u7684\u7aef\uff1a", None))
        self.cbox_type.setItemText(0, QCoreApplication.translate("Dialog", u"Paper", None))
        self.cbox_type.setItemText(1, QCoreApplication.translate("Dialog", u"Forge", None))
        self.cbox_type.setItemText(2, QCoreApplication.translate("Dialog", u"Vanilla", None))
        self.cbox_type.setItemText(3, QCoreApplication.translate("Dialog", u"Bukkit", None))
        self.cbox_type.setItemText(4, QCoreApplication.translate("Dialog", u"Spigot", None))
        self.cbox_type.setItemText(5, QCoreApplication.translate("Dialog", u"Mojang", None))
        self.cbox_type.setItemText(6, QCoreApplication.translate("Dialog", u"Nukkit", None))
        self.cbox_type.setItemText(7, QCoreApplication.translate("Dialog", u"CubeRite", None))
        self.cbox_type.setItemText(8, QCoreApplication.translate("Dialog", u"GlowStone", None))
        self.cbox_type.setItemText(9, QCoreApplication.translate("Dialog", u"Akarin", None))
        self.cbox_type.setItemText(10, QCoreApplication.translate("Dialog", u"BunggeeCord", None))
        self.cbox_type.setItemText(11, QCoreApplication.translate("Dialog", u"BukkitPlugins", None))
        self.cbox_type.setItemText(12, QCoreApplication.translate("Dialog", u"TacoSpigot", None))
        self.cbox_type.setItemText(13, QCoreApplication.translate("Dialog", u"Cauldron", None))
        self.cbox_type.setItemText(14, QCoreApplication.translate("Dialog", u"Thermos", None))
        self.cbox_type.setItemText(15, QCoreApplication.translate("Dialog", u"WaterFall", None))
        
        self.pbtn_ok2.setText(QCoreApplication.translate("Dialog", u"\u786e\u8ba4", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"\u8981\u4e0b\u8f7d\u7aef\u7248\u672c\uff1a", None))
        self.cbox_ver.setItemText(0, QCoreApplication.translate("Dialog", u"1.18.1", None))
        self.cbox_ver.setItemText(1, QCoreApplication.translate("Dialog", u"1.18", None))
        self.cbox_ver.setItemText(2, QCoreApplication.translate("Dialog", u"1.17.1", None))
        self.cbox_ver.setItemText(3, QCoreApplication.translate("Dialog", u"1.17", None))
        self.cbox_ver.setItemText(4, QCoreApplication.translate("Dialog", u"1.16.5", None))
        self.cbox_ver.setItemText(5, QCoreApplication.translate("Dialog", u"1.16.4", None))
        self.cbox_ver.setItemText(6, QCoreApplication.translate("Dialog", u"1.16.3", None))
        self.cbox_ver.setItemText(7, QCoreApplication.translate("Dialog", u"1.16.2", None))
        self.cbox_ver.setItemText(8, QCoreApplication.translate("Dialog", u"1.16.1", None))
        self.cbox_ver.setItemText(9, QCoreApplication.translate("Dialog", u"1.16", None))
        self.cbox_ver.setItemText(10, QCoreApplication.translate("Dialog", u"1.15.2", None))
        self.cbox_ver.setItemText(11, QCoreApplication.translate("Dialog", u"1.15.1", None))
        self.cbox_ver.setItemText(12, QCoreApplication.translate("Dialog", u"1.15", None))
        self.cbox_ver.setItemText(13, QCoreApplication.translate("Dialog", u"1.14.4", None))
        self.cbox_ver.setItemText(14, QCoreApplication.translate("Dialog", u"1.14.3", None))
        self.cbox_ver.setItemText(15, QCoreApplication.translate("Dialog", u"1.14.2", None))
        self.cbox_ver.setItemText(16, QCoreApplication.translate("Dialog", u"1.14.1", None))
        self.cbox_ver.setItemText(17, QCoreApplication.translate("Dialog", u"1.14", None))
        self.cbox_ver.setItemText(18, QCoreApplication.translate("Dialog", u"1.13.2", None))
        self.cbox_ver.setItemText(19, QCoreApplication.translate("Dialog", u"1.13.1", None))
        self.cbox_ver.setItemText(20, QCoreApplication.translate("Dialog", u"1.13", None))
        self.cbox_ver.setItemText(21, QCoreApplication.translate("Dialog", u"1.12.2", None))
        self.cbox_ver.setItemText(22, QCoreApplication.translate("Dialog", u"1.12.1", None))
        self.cbox_ver.setItemText(23, QCoreApplication.translate("Dialog", u"1.12", None))
        self.cbox_ver.setItemText(24, QCoreApplication.translate("Dialog", u"1.11.2", None))
        self.cbox_ver.setItemText(25, QCoreApplication.translate("Dialog", u"1.11.1", None))
        self.cbox_ver.setItemText(26, QCoreApplication.translate("Dialog", u"1.11", None))
        self.cbox_ver.setItemText(27, QCoreApplication.translate("Dialog", u"1.10.2", None))
        self.cbox_ver.setItemText(28, QCoreApplication.translate("Dialog", u"1.10.1", None))
        self.cbox_ver.setItemText(29, QCoreApplication.translate("Dialog", u"1.10", None))
        self.cbox_ver.setItemText(30, QCoreApplication.translate("Dialog", u"1.9.4", None))
        self.cbox_ver.setItemText(31, QCoreApplication.translate("Dialog", u"1.9.3", None))
        self.cbox_ver.setItemText(32, QCoreApplication.translate("Dialog", u"1.9.2", None))
        self.cbox_ver.setItemText(33, QCoreApplication.translate("Dialog", u"1.9.1", None))
        self.cbox_ver.setItemText(34, QCoreApplication.translate("Dialog", u"1.9", None))
        self.cbox_ver.setItemText(35, QCoreApplication.translate("Dialog", u"1.8.9", None))
        self.cbox_ver.setItemText(36, QCoreApplication.translate("Dialog", u"1.8.8", None))
        self.cbox_ver.setItemText(37, QCoreApplication.translate("Dialog", u"1.8.7", None))
        self.cbox_ver.setItemText(38, QCoreApplication.translate("Dialog", u"1.8.6", None))
        self.cbox_ver.setItemText(39, QCoreApplication.translate("Dialog", u"1.8.5", None))
        self.cbox_ver.setItemText(40, QCoreApplication.translate("Dialog", u"1.8.4", None))
        self.cbox_ver.setItemText(41, QCoreApplication.translate("Dialog", u"1.8.3", None))
        self.cbox_ver.setItemText(42, QCoreApplication.translate("Dialog", u"1.8.2", None))
        self.cbox_ver.setItemText(43, QCoreApplication.translate("Dialog", u"1.8.1", None))
        self.cbox_ver.setItemText(44, QCoreApplication.translate("Dialog", u"1.8", None))
        self.cbox_ver.setItemText(45, QCoreApplication.translate("Dialog", u"1.7.9", None))
        self.cbox_ver.setItemText(46, QCoreApplication.translate("Dialog", u"1.7.8", None))
        self.cbox_ver.setItemText(47, QCoreApplication.translate("Dialog", u"1.7.7", None))
        self.cbox_ver.setItemText(48, QCoreApplication.translate("Dialog", u"1.7.6", None))
        self.cbox_ver.setItemText(49, QCoreApplication.translate("Dialog", u"1.7.5", None))
        self.cbox_ver.setItemText(50, QCoreApplication.translate("Dialog", u"1.7.4", None))
        self.cbox_ver.setItemText(51, QCoreApplication.translate("Dialog", u"1.7.3", None))
        self.cbox_ver.setItemText(52, QCoreApplication.translate("Dialog", u"1.7.2", None))
        self.cbox_ver.setItemText(53, QCoreApplication.translate("Dialog", u"1.7.1", None))
        self.cbox_ver.setItemText(54, QCoreApplication.translate("Dialog", u"1.7", None))
        
        self.pbtn_start_download.setText(QCoreApplication.translate("Dialog", u"\u5f00\u59cb\u4e0b\u8f7d", None))
    # retranslateUi
