# -*- coding: utf-8 -*-

### 这是由机器生成的，正常情况下并不需要改动此文件，所以没有注释 ###

################################################################################
## Form generated from reading UI file 'download.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(483, 43)
        self.pbtn_start_download = QPushButton(Dialog)
        self.pbtn_start_download.setObjectName(u"pbtn_start_download")
        self.pbtn_start_download.setGeometry(QRect(390, 10, 80, 22))
        self.cbox_type = QComboBox(Dialog)
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.addItem("")
        self.cbox_type.setObjectName(u"cbox_type")
        self.cbox_type.setGeometry(QRect(10, 10, 241, 22))
        self.comboBox = QComboBox(Dialog)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(260, 10, 121, 22))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.pbtn_start_download.setText(QCoreApplication.translate("Dialog", u"\u5f00\u59cb\u4e0b\u8f7d", None))
        self.cbox_type.setItemText(0, QCoreApplication.translate("Dialog", u"Paper", None))
        self.cbox_type.setItemText(1, QCoreApplication.translate("Dialog", u"Forge", None))
        self.cbox_type.setItemText(2, QCoreApplication.translate("Dialog", u"Vanilla", None))
        self.cbox_type.setItemText(3, QCoreApplication.translate("Dialog", u"Bukkit", None))
        self.cbox_type.setItemText(4, QCoreApplication.translate("Dialog", u"Spigot", None))
        self.cbox_type.setItemText(5, QCoreApplication.translate("Dialog", u"Mojang", None))
        self.cbox_type.setItemText(6, QCoreApplication.translate("Dialog", u"Nukkit", None))
        self.cbox_type.setItemText(7, QCoreApplication.translate("Dialog", u"CubeRite", None))
        self.cbox_type.setItemText(8, QCoreApplication.translate("Dialog", u"GlowStone", None))
        self.cbox_type.setItemText(9, QCoreApplication.translate("Dialog", u"Akarin", None))
        self.cbox_type.setItemText(10, QCoreApplication.translate("Dialog", u"BunggeeCord", None))
        self.cbox_type.setItemText(11, QCoreApplication.translate("Dialog", u"BukkitPlugins", None))
        self.cbox_type.setItemText(12, QCoreApplication.translate("Dialog", u"TacoSpigot", None))
        self.cbox_type.setItemText(13, QCoreApplication.translate("Dialog", u"Cauldron", None))
        self.cbox_type.setItemText(14, QCoreApplication.translate("Dialog", u"Thermos", None))
        self.cbox_type.setItemText(15, QCoreApplication.translate("Dialog", u"WaterFall", None))

        self.comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"1.18.1", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"1.18", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Dialog", u"1.17.1", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("Dialog", u"1.17", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("Dialog", u"1.16.5", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("Dialog", u"1.16.4", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("Dialog", u"1.16.3", None))
        self.comboBox.setItemText(7, QCoreApplication.translate("Dialog", u"1.16.2", None))
        self.comboBox.setItemText(8, QCoreApplication.translate("Dialog", u"1.16.1", None))
        self.comboBox.setItemText(9, QCoreApplication.translate("Dialog", u"1.16", None))
        self.comboBox.setItemText(10, QCoreApplication.translate("Dialog", u"1.15.2", None))
        self.comboBox.setItemText(11, QCoreApplication.translate("Dialog", u"1.15.1", None))
        self.comboBox.setItemText(12, QCoreApplication.translate("Dialog", u"1.15", None))
        self.comboBox.setItemText(13, QCoreApplication.translate("Dialog", u"1.14.4", None))
        self.comboBox.setItemText(14, QCoreApplication.translate("Dialog", u"1.14.3", None))
        self.comboBox.setItemText(15, QCoreApplication.translate("Dialog", u"1.14.2", None))
        self.comboBox.setItemText(16, QCoreApplication.translate("Dialog", u"1.14.1", None))
        self.comboBox.setItemText(17, QCoreApplication.translate("Dialog", u"1.14", None))
        self.comboBox.setItemText(18, QCoreApplication.translate("Dialog", u"1.13.2", None))
        self.comboBox.setItemText(19, QCoreApplication.translate("Dialog", u"1.13.1", None))
        self.comboBox.setItemText(20, QCoreApplication.translate("Dialog", u"1.13", None))
        self.comboBox.setItemText(21, QCoreApplication.translate("Dialog", u"1.12.2", None))
        self.comboBox.setItemText(22, QCoreApplication.translate("Dialog", u"1.12.1", None))
        self.comboBox.setItemText(23, QCoreApplication.translate("Dialog", u"1.12", None))
        self.comboBox.setItemText(24, QCoreApplication.translate("Dialog", u"1.11.2", None))
        self.comboBox.setItemText(25, QCoreApplication.translate("Dialog", u"1.11.1", None))
        self.comboBox.setItemText(26, QCoreApplication.translate("Dialog", u"1.11", None))
        self.comboBox.setItemText(27, QCoreApplication.translate("Dialog", u"1.10.2", None))
        self.comboBox.setItemText(28, QCoreApplication.translate("Dialog", u"1.10.1", None))
        self.comboBox.setItemText(29, QCoreApplication.translate("Dialog", u"1.10", None))
        self.comboBox.setItemText(30, QCoreApplication.translate("Dialog", u"1.9.4", None))
        self.comboBox.setItemText(31, QCoreApplication.translate("Dialog", u"1.9.3", None))
        self.comboBox.setItemText(32, QCoreApplication.translate("Dialog", u"1.9.2", None))
        self.comboBox.setItemText(33, QCoreApplication.translate("Dialog", u"1.9.1", None))
        self.comboBox.setItemText(34, QCoreApplication.translate("Dialog", u"1.9", None))
        self.comboBox.setItemText(35, QCoreApplication.translate("Dialog", u"1.8.9", None))
        self.comboBox.setItemText(36, QCoreApplication.translate("Dialog", u"1.8.8", None))
        self.comboBox.setItemText(37, QCoreApplication.translate("Dialog", u"1.8.7", None))
        self.comboBox.setItemText(38, QCoreApplication.translate("Dialog", u"1.8.6", None))
        self.comboBox.setItemText(39, QCoreApplication.translate("Dialog", u"1.8.5", None))
        self.comboBox.setItemText(40, QCoreApplication.translate("Dialog", u"1.8.4", None))
        self.comboBox.setItemText(41, QCoreApplication.translate("Dialog", u"1.8.3", None))
        self.comboBox.setItemText(42, QCoreApplication.translate("Dialog", u"1.8.2", None))
        self.comboBox.setItemText(43, QCoreApplication.translate("Dialog", u"1.8.1", None))
        self.comboBox.setItemText(44, QCoreApplication.translate("Dialog", u"1.8", None))
        self.comboBox.setItemText(45, QCoreApplication.translate("Dialog", u"1.7.9", None))
        self.comboBox.setItemText(46, QCoreApplication.translate("Dialog", u"1.7.8", None))
        self.comboBox.setItemText(47, QCoreApplication.translate("Dialog", u"1.7.7", None))
        self.comboBox.setItemText(48, QCoreApplication.translate("Dialog", u"1.7.6", None))
        self.comboBox.setItemText(49, QCoreApplication.translate("Dialog", u"1.7.5", None))
        self.comboBox.setItemText(50, QCoreApplication.translate("Dialog", u"1.7.4", None))
        self.comboBox.setItemText(51, QCoreApplication.translate("Dialog", u"1.7.3", None))
        self.comboBox.setItemText(52, QCoreApplication.translate("Dialog", u"1.7.2", None))
        self.comboBox.setItemText(53, QCoreApplication.translate("Dialog", u"1.7.1", None))
        self.comboBox.setItemText(54, QCoreApplication.translate("Dialog", u"1.7", None))

    # retranslateUi

